template: cv-academic

contents:
  education:
    - phd
    - isp
    - mscthesis
    - undergrad

  jobs:
    - pasteur
    - gras
    - hiwi

  projects:
    - madgod

  software:
    - veros
    - mpi4jax
