template: resume

contents:
  education:
    - phd
    - undergrad

  jobs:
    - pasteur
    - gras

  projects:
    - madgod

  software:
    - veros
    - terracotta

  technology:
    - ml
    - python
