personal:
  name: Dion Häfner
  jobtitle: Programming Scientist | Scientific Programmer
  address: Malmö, Sweden
  email: mail@dionhaefner.de
  github: dionhaefner
  homepage: dionhaefner.github.io
  scholar: 8jzVkXEAAAAJ
  twitter: dionhaefner
  linkedin: dionhaefner
  spotify: "1214862881"


tagline: >
  I am a Physicist specialized on all things scientific computing,
  with industry experience in data processing and machine learning.

  My main research interest is ``human learning'': How can we build machines
  that teach us something about our physical world?


jobs:
  pasteur:
    company: Pasteur Labs
    title: Research Engineer
    location: Remote
    start: 04-04-2022
    end:
    long-description: >
      I build efficient, scalable software for scientific advances in all areas
      of simulation intelligence (SI). This includes differentiable programming,
      earth systems simulation, physics-infused machine learning, probabilistic
      machine learning and computation, simulation based inference, and
      causal machine learning.
    description: >
      I build efficient, scalable software for scientific advances at the interface
      between physical simulators and modern machine learning.

  gras:
    company: DHI GRAS
    title: Software development specialist
    location: Hørsholm, Denmark
    start: 01-09-2017
    end: 01-12-2018
    long-description: >
      At DHI GRAS, I built robust data pipelines and powerful machine
      learning tools on satellite images. Through low-level optimizations
      on one particularly expensive algorithm, I was able to cut processing
      times by over 3 orders of magnitude (from weeks to hours), while
      minimizing human supervision.
    description: >
      At DHI GRAS, I built robust data pipelines, powerful statistical tools,
      and optimized remote sensing workflows.

  veros:
    company: Niels Bohr Institute
    title: Scientific assistant
    location: Copenhagen, Denmark
    start: 01-01-2017
    end: 01-08-2017
    long-description: >
      I am the main developer of a full-blown, distributed ocean model
      written in pure Python with full GPU support (\emph{Veros},
      available on GitHub).
      Large simulations are only about 2 times slower than a Fortran
      reference implementation, while being orders of magnitude more
      approachable for students and scientists.
    description: >
      I developed the first prototype of Veros, a high-performance ocean model in Python.

  hiwi:
    company: Institute of Environmental Physics
    title: Research assistant
    location: Heidelberg, Germany
    start: 01-06-2014
    end: 01-12-2016
    long-description: >
      I enhanced a numerical simulation package based on the DUNE framework
      (\emph{DORiE}), written in C++ and Python.
      By implementing adaptive grid refinement, I was able to speed up
      simulations by a factor of up to 100.
    description: >
      Working in a small team of developers on a numerical software suite
      for soil water flow (discontinuous Galerkin PDE solver), in C++ and Python.

education:
  phd:
    start: 01-12-2018
    end: 01-04-2022
    title: PhD in Physical Oceanography
    institution: University of Copenhagen
    long-description: >
      In my PhD project at the Niels Bohr Institute (Prof. Markus Jochum)
      I inferred the relative importance of hypothesized causes
      of extreme ocean waves (``rogue waves'') in the real world.
      To this end, I analyzed over 1 Terabyte of observational data
      with data mining and probabilistic machine learning to extract
      robust, causal insights.
    description: >
      In my project, I used machine learning on large amounts of
      real-world data to infer by which physical mechanisms extreme ocean
      waves (rogue waves) are generated.

  isp:
    start: 01-09-2021
    end: 01-12-2021
    title: Research visit
    institution: University of Valencia
    long-description: >
      During my 3-month research visit to the Image Processing Lab
      (Prof. Gustau Camps-Valls) I investigated how machine learning can
      help humans to understand climate models.
    description: >
      During my 3-month research visit to the Image Processing Lab
      (Prof. Gustau Camps-Valls) I investigated how machine learning can
      help humans to understand climate models.

  mscthesis:
    start: 01-09-2015
    end: 01-12-2016
    title: External Master's thesis in Physical Oceanography
    institution: University of Copenhagen
    long-description: >
      Working with state-of-the-art climate models, I learned how to
      process and analyze large quantities of data, and became familiar
      with geoscientific modeling and high-performance computing.
    description: >
      Running climate models on the DC3 cluster, data evaluation,
      theoretical examination of large-scale ocean currents,
      implementation of a reduced-gravity model.

  undergrad:
    start: 01-09-2011
    end: 01-12-2016
    title: BSc and MSc in Physics
    institution: Heidelberg University
    long-description: >
      GPA of 1.3 and 1.2, respectively (``very good'').
      Exchange year at KTH Stockholm in 2014.
      Specialization on computational physics.
    description: >
      GPA of 1.3 and 1.2, respectively (``very good'').
      Exchange year at KTH Stockholm in 2014.
      Specialization on computational physics.

  msc:
    start: 01-09-2015
    end: 01-12-2016
    title: Master of Science (MSc) in Physics
    institution: Heidelberg University
    long-description: >
      GPA of 1.2 (``very good''). Specialization in computational physics.

      External Master's thesis
      \emph{``Frictional Control of Cross-Equatorial Flow''}
      in Physical Oceanography at Niels Bohr Institute, \highlight{University of Copenhagen}
      (Prof. Markus Jochum).
    description: >
      GPA of 1.2 (``very good''). Specialization in computational physics.

  bsc:
    start: 01-09-2011
    end: 01-09-2015
    title: Bachelor of Science (BSc) in Physics
    institution: Heidelberg University
    long-description: >
      GPA of 1.3 (``very good'').

      Bachelor's thesis
      \emph{``Numerical Simulations of Soil Water Flow: Implementing and Benchmarking Adaptive Grid Refinement''}
      at Terrestrial Physics group, IUP Heidelberg (Prof. Kurt Roth).

      Exchange year 2013/2014 at \highlight{KTH Stockholm}, specializing on computational physics.
    description: >
      GPA of 1.3 (``very good'').


projects:
  veros:
    title: Veros --- A high-performance ocean model in pure Python
    description: >
       I am the main developer and maintainer of Veros, a full-fledged primitive equation
       ocean model capable of accurate, realistic simulations of the global ocean.
       It leverages the JAX library for state-of-the-art performance on CPU and GPU clusters.
    website: https://github.com/team-ocean/veros
  terracotta:
    title: Terracotta --- A light-weight geospatial raster tile server
    description: >
      Terracotta is a cloud-ready raster tile server,
      leveraging the cloud-optimized GeoTiff format
      and a modern geospatial Python stack.
    website: https://github.com/DHI-GRAS/terracotta
  mpi4jax:
    title: mpi4jax --- Zero-copy MPI communication of JAX arrays
    description: >
      mpi4jax enables zero-copy, multi-host communication of JAX arrays, even from compiled code
      and from GPU memory.
    website: https://github.com/mpi4jax/mpi4jax


teaching:
  courses: >
    3 Teaching Assistant (TA) assignments in Physics MSc courses at the Niels Bohr Institute.
    Nominated for biannual TA prize in 2021.
  theses: >
    Co-supervisor to 1 BSc student and 1 MSc student at NBI.
    Closely involved in 5 MSc projects from other departments / universities.


technology:
  ml:
    title: ML frameworks
    long-description: >
      I am familiar with modern machine learning workflows and have good
      knowledge of scikit-learn, Tensorflow / Keras, PyMC, and JAX.

  python:
    title: Python
    long-description: >
      I have both deep and broad experience within the Python ecosystem,
      especially concerning (but not limited to) \highlight{data analysis,
      machine learning, visualization, and scientific computing}.
      I love working with the modern scientific Python stack and am
      well-versed with NumPy, SciPy, matplotlib, xarray, JAX, Numba,
      and Pandas.

  otherlang:
    title: Other languages
    long-description: >
      Basic knowledge of object-oriented programming in C++, including
      debugging applications with GDB. Elementary knowledge of OpenCL / CUDA.

  tools:
    title: Tools
    long-description: >
      Experience with tools handling version control (git), documentation
      (Sphinx, Doxygen), build systems (CMake), deployment (Docker),
      testing (pytest), GUI (Qt), continuous integration
      (Travis CI / Github Actions), and typesetting (\LaTeX).

      I am comfortable working in all major operating systems, and am
      familiar with basic server administration tasks, including cloud providers
      like AWS and GCP.


talks:
  invited:
    drakkar-2022:
      title: JAX of all trades — GPU-accelerated ocean modelling in Python
      type: Keynote presentation
      date: 02-02-2022
      venue: DRAKKAR ocean modelling workshop (virtual)
    egu-presentation-2022:
      title: Painless science posters
      type: Presentation
      date: 02-05-2022
      venue: EGU webinar "Be ready to be a great conference presenter" (virtual)


awards:
  phd-award:
    title: Diploma of Excellence (top 10 PhD thesis of 2022)
    institution: Faculty of SCIENCE, University of Copenhagen
    date: 01-09-2022
    
  egu-vospp:
    title: Virtual Outstanding Student and PhD candidate Presentation (vOSPP)
    institution: European Geophysical Union
    date: 01-11-2021


other:
  maths: >
    Strong \highlight{mathematical and analytical skills}, and an affection
    for data.
  numerics: >
    Good theoretical foundation of \highlight{applied mathematics and scientific
    computing} (including ODE / PDE solvers, numerical optimization,
    signal processing, and automatic differentiation).
  bayes: >
    A knack for probabilistic reasoning and \highlight{Bayesian data analysis}:
    I like to make my assumptions and uncertainties explicit.
  oss: >
    I am passionate about \highlight{open-source software development},
    and have contributed code to several big projects on GitHub.
  comm: >
    A special interest in \highlight{effective communication}
    through writing, oral presentations, and data visualization.
    I take the quality of my publications seriously, and love to
    present my work.


languages:
  de:
    lang: German
    skill: native
  en:
    lang: English
    skill: fully proficient
  se:
    lang: Swedish
    skill: proficient
  dk:
    lang: Danish
    skill: elementary


references:
  markus:
    name: Markus Jochum
    email: mjochum@nbi.ku.dk
    occupation: Professor, Niels Bohr Institute, University of Copenhagen, Denmark
  gustau:
    name: Gustau Camps-Valls
    email: gustau.camps@uv.es
    occupation: Professor, Image Processing Lab, University of Valencia, Spain
  johannes:
    name: Johannes Gemmrich
    email: gemmrich@uvic.ca
    occupation: Research Scientist, Physics & Astronomy, University of Victoria, Canada


publications:
  veros-jax:
    doi: "10.1029/2021MS002717"
  mpi4jax:
    doi: "10.21105/joss.03419"
  fowd:
    doi: "10.1175/JTECH-D-20-0185.1"
  rogueprob:
    doi: "10.1038/s41598-021-89359-1"
  dorie:
    doi: "10.21105/joss.02313"
  veros:
    doi: "10.5194/gmd-11-3299-2018"
